:warning-caption: :warning:

JCProfilerNext
==============

link:https://github.com/lzaoral/JCProfilerNext/actions/workflows/ci.yml[image:https://github.com/lzaoral/JCProfilerNext/actions/workflows/ci.yml/badge.svg[Java CI with Gradle]]

WARNING: JCProfilerNext is still a work in progress so changes in behaviour,
bugs and crashes are expected.  If you encounter a bug, please file an issue.
Thank you!

JCProfilerNext is a complete rewrite of link:https://github.com/OpenCryptoProject/JCProfiler[OpenCryptoProject/JCProfiler]
that provides a completely automated preprocessing, compilation, installation
and profiling of JavaCard code on JavaCard smart cards or in the jCardSim
simulator.

Prerequisites
-------------

Install JDK 8 or newer.

Installation
------------

. Clone this repository.
. Run `./gradlew build` on Unix-like systems or `gradlew.bat build` on Windows.
. Execute
.. directly using Gradle: `./gradlew run --args='--help'`.
.. directly using built JAR: `java -jar build/libs/javacard-profiler-1.0-SNAPSHOT.jar --help`.
.. directly from distribution archives in `build/distributions`.

Example
-------
Consider the `example` method in the following class.  The outer loop is clearly
not constant since its iteration count depends on the input value.  On the other
hand, the inner loop is constant.

[source,java]
----
package example;

import javacard.framework.*;

public class Example extends Applet {
    public static final byte INS_EXAMPLE = (byte) 0xEE;

    Example() { }

    public static void install(byte[] bArray, short bOffset, byte bLength) {
        new Example().register();
    }

    @Override
    public void process(APDU apdu) throws ISOException {
        if (selectingApplet())
            return;

        switch (apdu.getBuffer()[ISO7816.OFFSET_INS]) {
            case INS_EXAMPLE:
                example(apdu);
                break;
            default:
                ISOException.throwIt(ISO7816.SW_INS_NOT_SUPPORTED);
        }
    }

    private void example(APDU apdu) {
        short count = Util.getShort(apdu.getBuffer(), ISO7816.OFFSET_CDATA);
        for (short i = 0; i < count; i++) {
            short tmp = 0;
            for (short k = 0; k < 50; k++) {
                tmp++;
            }
        }
    }
}
----

Run as:
[source,console]
----
$ ./gradlew run --args="--work-dir example --jckit jc222_kit -o output --method example --inst 0xEE --data-regex 00[0-9A-F]{2} --repeat-count 100"
----
JCProfilerNext will process all sources in the `example` directory and will
also use this directory to store all intermediate results:

* `applet` - contains the built applet with corresponding CAP and JAR files
* `measurements.csv` - contains raw measurements
* `measurements.html` - contains visualisation of the measurements
* `sources_instr` - contains instrumented sources
* `sources_original` - contains original unchanged sources
* `sources_perf` - contains sources with inserted measurements as inline comments

If you open the corresponding link:https://lzaoral.github.io/JCProfilerNext/example.html[`measurements.html`]
produced by JCProfilerNext, you will see that some parts of the code are indeed
not constant.  Namely if you inspect the corresponding histograms of traps
after the `for` loops.

Limitations
-----------

* Cards that require special communication procedures are not supported.
* Instrumentation and profiling of nested classes may fail.
* It is not possible to use a different JDK to compile the JavaCard applets and to run this project.
* Instrumentation of distinct methods that have the same simple name is not supported.
* Connection to wireless card terminals may occasionally fail.
